name: github pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.113.0'

      - name: Inject G-Tag
        run: sed -i 's/G-JXMPBB9GZR/G-T2L6R32KL8/g' config.json

      - name: Build
        run: hugo --minify -b 'https://megolang.com/'

      - name: add CNAME
        run: echo "megolang.com" > ./public/CNAME
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          external_repository: mingkyme/megolang.com
          publish_dir: ./public
